# Generated by Django 3.0.7 on 2022-12-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.IntegerField()),
                ('bio', models.TextField(max_length=500)),
                ('course_name', models.CharField(max_length=20)),
                ('course_duration', models.IntegerField()),
                ('course_passout_year', models.IntegerField()),
                ('course_percentage', models.IntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('duration_of_job', models.IntegerField()),
                ('job_desc', models.TextField(max_length=500)),
                ('sallary', models.IntegerField()),
                ('project_name', models.CharField(max_length=255)),
                ('project_duration', models.IntegerField()),
                ('project_description', models.TextField(max_length=500)),
                ('your_role_in_project', models.TextField(max_length=300)),
            ],
        ),
    ]
